version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - PYTHONPATH=/app  
    volumes:
      - ./app:/app
      - sqlite_data:/app/db
      - static_volume:${STATIC_ROOT}
    ports:
      - "8000:8000"
volumes:
  sqlite_data:
  static_volume: